### ISSUE TITLE
cabal install missing dependencies

### ISSUE THREAD

**Issue by Andrea** [elisehuard/game-in-haskell#2]
Hi there

This is probably a problem with my setup but I am not sure where else to search

I run cabal install --only-dependencies 

and I am getting the following error

```
mo@mo-VirtualBox:~/dev/game-in-haskell$ cabal install --only-dependencies
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: game-in-haskell-book-0.1.0.0 (user goal)
next goal: base (dependency of game-in-haskell-book-0.1.0.0)
rejecting: base-4.6.0.1/installed-ced... (conflict: game-in-haskell-book =>
base>=4.7 && <4.8)
rejecting: base-4.7.0.2, 4.7.0.1, 4.7.0.0, 4.6.0.1, 4.6.0.0, 4.5.1.0, 4.5.0.0,
4.4.1.0, 4.4.0.0, 4.3.1.0, 4.3.0.0, 4.2.0.2, 4.2.0.1, 4.2.0.0, 4.1.0.0,
4.0.0.0, 3.0.3.2, 3.0.3.1 (global constraint requires installed instance)
Dependency tree exhaustively searched.

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.

```

I tried runghc configure and

```
monad@monad-VirtualBox:~/dev/game-in-haskell$ runghc Setup.hs configureConfiguring game-in-haskell-book-0.1.0.0...
Setup.hs: At least the following dependencies are missing:
ALUT ==2.3.0.2,
GLFW-b ==1.4.6,
base ==4.7.*,
elerea ==2.8.0,
gloss ==1.9.2.1,
gloss-rendering ==1.9.2.1,
random ==1.1,
text ==1.2.0.4

```

I installed libghc-alut-dev but the version on that seems to 2.2.0.0 

I am on ubuntu 14.10
cabal 1.20.0.2
ghc 7.6.3

Any ideas?

FYI I tried running the GLFW sample and that runs fine :(

**Comment by dino-** [comment]
Andrea,

What I believe you're seeing is that the version of the base Haskell library for `ghc` 7.6.x is 4.6.0.1 but the `game-in-haskell` project requires >=4.7 && <4.8. It's not that uncommon for the tools to be old-ish like this on stock systems.

So, let's fix that. What I do for a more modern `ghc` on debian-like systems is this:

First, install this PPA

```
# add-apt-repository ppa:hvr/ghc
# sudo apt-get update
```

Then the compiler and cabal

```
# sudo apt-get install ghc-7.8.4
# sudo apt-get install cabal-install-1.22
```

These are installed in `/opt/ghc/7.8.4` and `/opt/cabal/1.22`. The best thing to do is add those dirs plus `bin` to your `PATH`

More details on this can be found at the [page for this PPA](https://launchpad.net/~hvr/+archive/ubuntu/ghc)

But this should get you a working and pretty fresh `ghc` and `cabal` setup, close to what I'm seeing work. I used this PPA in the past month to get a Ubuntu 14.04 system up to speed for another project.

Let us know if this works for you. If not, we'll figure out why.

**Comment by Andrea** [comment]
Hi dino

Thanks for the answer. I just ran all that and no luck. I am using linux for the first time in a long time because I imagined following the book on windows might be actually harder than this ( dependencies more than anything else). So not sure I added stuff to the path correctly 
To add I went to .profile and added the following

```
PATH="$PATH:/opt/ghc/7.8.4"
PATH="$PATH:/opt/ghc/7.8.4/bin"
PATH="$PATH:/opt/cabal/1.22"
PATH="$PATH:/opt/cabal/1.22/bin"
```

at the bottom of the file :?
(I rebooted after just in case)

all the other commands ran without error :D but I checked and I still am on 7.6.3 for ghc :crying_cat_face:

**Comment by dino-** [comment]
On Thu, Mar 05, 2015 at 08:06:40AM -0800, Andrea wrote:

>    Hi dino
> 
>    Thanks for the answer. I just ran all that and no luck. I am using
>    linux for the first time in a long time because I imagined following
>    the book on windows might be actually harder than this ( dependencies
>    more than anything else). So not sure I added stuff to the path
>    correctly
>    To add I went to .profile and added the following
> PATH="$PATH:/opt/ghc/7.8.4"
> PATH="$PATH:/opt/ghc/7.8.4/bin"
> PATH="$PATH:/opt/cabal/1.22"
> PATH="$PATH:/opt/cabal/1.22/bin"
> 
>    at the bottom of the file :?
> 
>    all the other commands ran without error :D but I checked and I still
>    am on 7.6.3 for ghc :(

You want to put those paths ahead of the existing PATH, like this:

```
PATH="/opt/ghc/7.8.4/bin:$PATH"
PATH="/opt/cabal/1.22/bin:$PATH"
```

And no need to have the other not-bin paths, I don't think.

## 

Dino Morelli | dino@ui3.info | http://ui3.info/d/

**Comment by Andrea** [comment]
Trying that now, it's looking good  :)
downloading the internet..

**Comment by Andrea** [comment]
that builds :smile: 
Thanks  for the help
